"""
테스트용 mock 데이터를 생성하여 service-daemon에 주입합니다.
실제 파이프라인 없이 Portal의 Review/Report 기능을 테스트할 수 있습니다.
"""
import json
import os
import sys
import asyncio
# service-daemon 모듈 경로 추가
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.datetime_kst import now_kst_iso
from app.models import Job, OrderStatus


def create_mock_result_json(output_dir: str, sample_name: str = "SAMPLE_001"):
    """Carrier Screening result.json 예시 데이터를 생성합니다."""
    os.makedirs(output_dir, exist_ok=True)

    result = {
        "meta": {
            "order_id": "CS-TEST-001",
            "sample_name": sample_name,
            "service_code": "carrier_screening",
            "pipeline_version": "1.0.0",
            "analysis_date": now_kst_iso(),
            "reference_genome": "GRCh38",
        },
        "qc_summary": {
            "coverage": {
                "mean_coverage": 98.5,
                "median_coverage": 95.0,
                "pct_10x": 99.2,
                "pct_20x": 98.1,
                "pct_30x": 96.3,
            },
            "alignment": {
                "total_reads": 85000000,
                "mapped_reads": 84200000,
                "mapping_rate": 99.06,
                "properly_paired_rate": 98.2,
                "duplicates": 4500000,
                "average_quality": 36.5,
                "raw_total_sequences": 85000000,
            },
        },
        "variant_stats": {
            "total_variants": 15,
            "by_classification": {
                "Pathogenic": 3,
                "Likely pathogenic": 2,
                "VUS": 5,
                "Likely benign": 3,
                "Benign": 2,
            },
            "by_gene": {
                "CFTR": 3,
                "SMN1": 2,
                "GJB2": 2,
                "HBB": 2,
                "HEXA": 1,
                "PAH": 1,
                "GBA": 1,
                "ASPA": 1,
                "FANCC": 1,
                "MCOLN1": 1,
            },
            "by_effect": {
                "missense_variant": 7,
                "frameshift_variant": 2,
                "splice_donor_variant": 2,
                "nonsense_variant": 1,
                "synonymous_variant": 2,
                "intron_variant": 1,
            },
        },
        "variants": [
            {
                "variant_id": "chr7_117559590_G_A",
                "chrom": "chr7",
                "pos": 117559590,
                "ref": "G",
                "alt": "A",
                "gene": "CFTR",
                "transcript": "NM_000492.4",
                "canonical_enst": "ENST00000003084",
                "hgvsc": "c.1521_1523delCTT",
                "hgvsp": "p.Phe508del",
                "effect": "inframe_deletion",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 120,
                "ref_depth": 65,
                "alt_depth": 55,
                "vaf": 0.458,
                "gnomad_af": 0.0108,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Pathogenic",
                "clinvar_sig_primary": "Pathogenic",
                "clinvar_revstat": "reviewed by expert panel",
                "clinvar_stars": 4,
                "clinvar_dn": "Cystic fibrosis",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs113993960",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs113993960",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Cystic fibrosis",
                "curated_classification": "Pathogenic",
                "curated_source": "Internal DB v2.1",
                "inheritance": "AR",
                "acmg_classification": "Pathogenic",
                "acmg_criteria": ["PVS1", "PM2", "PP5"],
                "diseases": [
                    {"name": "Cystic fibrosis", "omim": "219700", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0002205", "name": "Recurrent respiratory infections"},
                    {"hpo_id": "HP:0002035", "name": "Chronic diarrhea"},
                    {"hpo_id": "HP:0004401", "name": "Meconium ileus"},
                ],
            },
            {
                "variant_id": "chr7_117587811_G_A",
                "chrom": "chr7",
                "pos": 117587811,
                "ref": "G",
                "alt": "A",
                "gene": "CFTR",
                "transcript": "NM_000492.4",
                "canonical_enst": "ENST00000003084",
                "hgvsc": "c.3846G>A",
                "hgvsp": "p.Trp1282Ter",
                "effect": "stop_gained",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 95,
                "ref_depth": 50,
                "alt_depth": 45,
                "vaf": 0.474,
                "gnomad_af": 0.0012,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Pathogenic",
                "clinvar_sig_primary": "Pathogenic",
                "clinvar_revstat": "reviewed by expert panel",
                "clinvar_stars": 4,
                "clinvar_dn": "Cystic fibrosis",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs77010898",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs77010898",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Cystic fibrosis",
                "curated_classification": "Pathogenic",
                "curated_source": "Internal DB v2.1",
                "inheritance": "AR",
                "acmg_classification": "Pathogenic",
                "acmg_criteria": ["PVS1", "PM2", "PP5"],
                "diseases": [
                    {"name": "Cystic fibrosis", "omim": "219700", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0002205", "name": "Recurrent respiratory infections"},
                ],
            },
            {
                "variant_id": "chr7_117590440_C_T",
                "chrom": "chr7",
                "pos": 117590440,
                "ref": "C",
                "alt": "T",
                "gene": "CFTR",
                "transcript": "NM_000492.4",
                "canonical_enst": "ENST00000003084",
                "hgvsc": "c.4056C>T",
                "hgvsp": "p.Arg1352Arg",
                "effect": "synonymous_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 110,
                "ref_depth": 60,
                "alt_depth": 50,
                "vaf": 0.455,
                "gnomad_af": 0.032,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Benign",
                "clinvar_sig_primary": "Benign",
                "clinvar_revstat": "criteria provided, multiple submitters",
                "clinvar_stars": 2,
                "clinvar_dn": "not provided",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs1800095",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs1800095",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": None,
                "hgmd_disease": None,
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "Benign",
                "acmg_criteria": ["BA1", "BP6"],
                "diseases": [],
                "hpo_phenotypes": [],
            },
            {
                "variant_id": "chr5_70924941_C_T",
                "chrom": "chr5",
                "pos": 70924941,
                "ref": "C",
                "alt": "T",
                "gene": "SMN1",
                "transcript": "NM_000344.4",
                "canonical_enst": "ENST00000380707",
                "hgvsc": "c.815A>G",
                "hgvsp": "p.Tyr272Cys",
                "effect": "missense_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 85,
                "ref_depth": 45,
                "alt_depth": 40,
                "vaf": 0.471,
                "gnomad_af": 0.00015,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Likely pathogenic",
                "clinvar_sig_primary": "Likely pathogenic",
                "clinvar_revstat": "criteria provided, single submitter",
                "clinvar_stars": 1,
                "clinvar_dn": "Spinal muscular atrophy",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs121909192",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs121909192",
                "clingen_hi_score": 3,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Spinal muscular atrophy",
                "curated_classification": "Likely pathogenic",
                "curated_source": "Internal DB v2.1",
                "inheritance": "AR",
                "acmg_classification": "Likely pathogenic",
                "acmg_criteria": ["PS3", "PM2", "PP3"],
                "diseases": [
                    {"name": "Spinal muscular atrophy", "omim": "253300", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0003202", "name": "Skeletal muscle atrophy"},
                    {"hpo_id": "HP:0001284", "name": "Areflexia"},
                ],
            },
            {
                "variant_id": "chr5_70925030_G_A",
                "chrom": "chr5",
                "pos": 70925030,
                "ref": "G",
                "alt": "A",
                "gene": "SMN1",
                "transcript": "NM_000344.4",
                "canonical_enst": "ENST00000380707",
                "hgvsc": "c.903+6T>G",
                "hgvsp": None,
                "effect": "intron_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 90,
                "ref_depth": 48,
                "alt_depth": 42,
                "vaf": 0.467,
                "gnomad_af": 0.005,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Uncertain significance",
                "clinvar_sig_primary": "VUS",
                "clinvar_revstat": "criteria provided, single submitter",
                "clinvar_stars": 1,
                "clinvar_dn": "Spinal muscular atrophy",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs200000001",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs200000001",
                "clingen_hi_score": 3,
                "clingen_ts_score": None,
                "hgmd_class": None,
                "hgmd_disease": None,
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "VUS",
                "acmg_criteria": ["PM2", "BP4"],
                "diseases": [
                    {"name": "Spinal muscular atrophy", "omim": "253300", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [],
            },
            {
                "variant_id": "chr13_20763612_G_A",
                "chrom": "chr13",
                "pos": 20763612,
                "ref": "G",
                "alt": "A",
                "gene": "GJB2",
                "transcript": "NM_004004.6",
                "canonical_enst": "ENST00000382844",
                "hgvsc": "c.35delG",
                "hgvsp": "p.Gly12ValfsTer2",
                "effect": "frameshift_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 130,
                "ref_depth": 70,
                "alt_depth": 60,
                "vaf": 0.462,
                "gnomad_af": 0.0089,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Pathogenic",
                "clinvar_sig_primary": "Pathogenic",
                "clinvar_revstat": "reviewed by expert panel",
                "clinvar_stars": 4,
                "clinvar_dn": "Nonsyndromic hearing loss",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs80338939",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs80338939",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Deafness, autosomal recessive 1A",
                "curated_classification": "Pathogenic",
                "curated_source": "Internal DB v2.1",
                "inheritance": "AR",
                "acmg_classification": "Pathogenic",
                "acmg_criteria": ["PVS1", "PM2", "PP5", "PM3"],
                "diseases": [
                    {"name": "Deafness, autosomal recessive 1A", "omim": "220290", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0000365", "name": "Hearing impairment"},
                    {"hpo_id": "HP:0000407", "name": "Sensorineural hearing impairment"},
                ],
            },
            {
                "variant_id": "chr13_20763686_C_T",
                "chrom": "chr13",
                "pos": 20763686,
                "ref": "C",
                "alt": "T",
                "gene": "GJB2",
                "transcript": "NM_004004.6",
                "canonical_enst": "ENST00000382844",
                "hgvsc": "c.109G>A",
                "hgvsp": "p.Val37Ile",
                "effect": "missense_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 115,
                "ref_depth": 60,
                "alt_depth": 55,
                "vaf": 0.478,
                "gnomad_af": 0.018,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Conflicting interpretations of pathogenicity",
                "clinvar_sig_primary": "VUS",
                "clinvar_revstat": "criteria provided, conflicting interpretations",
                "clinvar_stars": 1,
                "clinvar_dn": "Nonsyndromic hearing loss",
                "clinvar_conflicting": True,
                "clinvar_conflict_detail": "Pathogenic(3), Likely pathogenic(2), VUS(5), Likely benign(1)",
                "dbsnp_rsid": "rs72474224",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs72474224",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM?",
                "hgmd_disease": "Deafness, autosomal recessive 1A",
                "curated_classification": "VUS",
                "curated_source": "Internal DB v2.1",
                "inheritance": "AR",
                "acmg_classification": "VUS",
                "acmg_criteria": ["PM2", "PP3", "BP1"],
                "diseases": [
                    {"name": "Deafness, autosomal recessive 1A", "omim": "220290", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0000365", "name": "Hearing impairment"},
                ],
            },
            {
                "variant_id": "chr11_5226774_T_A",
                "chrom": "chr11",
                "pos": 5226774,
                "ref": "T",
                "alt": "A",
                "gene": "HBB",
                "transcript": "NM_000518.5",
                "canonical_enst": "ENST00000335295",
                "hgvsc": "c.20A>T",
                "hgvsp": "p.Glu7Val",
                "effect": "missense_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 105,
                "ref_depth": 55,
                "alt_depth": 50,
                "vaf": 0.476,
                "gnomad_af": 0.0045,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Pathogenic/Likely pathogenic",
                "clinvar_sig_primary": "Pathogenic",
                "clinvar_revstat": "reviewed by expert panel",
                "clinvar_stars": 4,
                "clinvar_dn": "Sickle cell disease",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs334",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs334",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Sickle cell anemia",
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "Likely pathogenic",
                "acmg_criteria": ["PS1", "PM2", "PP5"],
                "diseases": [
                    {"name": "Sickle cell disease", "omim": "603903", "inheritance": "AR"},
                    {"name": "Beta-thalassemia", "omim": "613985", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0001903", "name": "Anemia"},
                    {"hpo_id": "HP:0001744", "name": "Splenomegaly"},
                ],
            },
            {
                "variant_id": "chr11_5226838_C_T",
                "chrom": "chr11",
                "pos": 5226838,
                "ref": "C",
                "alt": "T",
                "gene": "HBB",
                "transcript": "NM_000518.5",
                "canonical_enst": "ENST00000335295",
                "hgvsc": "c.92+1G>A",
                "hgvsp": None,
                "effect": "splice_donor_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 88,
                "ref_depth": 46,
                "alt_depth": 42,
                "vaf": 0.477,
                "gnomad_af": 0.0002,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Uncertain significance",
                "clinvar_sig_primary": "VUS",
                "clinvar_revstat": "criteria provided, single submitter",
                "clinvar_stars": 1,
                "clinvar_dn": "Beta-thalassemia",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs200000002",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs200000002",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM?",
                "hgmd_disease": "Beta-thalassemia",
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "VUS",
                "acmg_criteria": ["PVS1", "PM2"],
                "diseases": [
                    {"name": "Beta-thalassemia", "omim": "613985", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0001903", "name": "Anemia"},
                ],
            },
            {
                "variant_id": "chr15_72638892_C_T",
                "chrom": "chr15",
                "pos": 72638892,
                "ref": "C",
                "alt": "T",
                "gene": "HEXA",
                "transcript": "NM_000520.6",
                "canonical_enst": "ENST00000261416",
                "hgvsc": "c.1278insTATC",
                "hgvsp": "p.Tyr427IlefsTer5",
                "effect": "frameshift_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 100,
                "ref_depth": 52,
                "alt_depth": 48,
                "vaf": 0.48,
                "gnomad_af": 0.0003,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Pathogenic",
                "clinvar_sig_primary": "Pathogenic",
                "clinvar_revstat": "reviewed by expert panel",
                "clinvar_stars": 4,
                "clinvar_dn": "Tay-Sachs disease",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs76173977",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs76173977",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Tay-Sachs disease",
                "curated_classification": "Pathogenic",
                "curated_source": "Internal DB v2.1",
                "inheritance": "AR",
                "acmg_classification": "Likely pathogenic",
                "acmg_criteria": ["PVS1", "PM2"],
                "diseases": [
                    {"name": "Tay-Sachs disease", "omim": "272800", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0001263", "name": "Global developmental delay"},
                    {"hpo_id": "HP:0001250", "name": "Seizures"},
                ],
            },
            {
                "variant_id": "chr12_103234210_G_A",
                "chrom": "chr12",
                "pos": 103234210,
                "ref": "G",
                "alt": "A",
                "gene": "PAH",
                "transcript": "NM_000277.3",
                "canonical_enst": "ENST00000553106",
                "hgvsc": "c.1222C>T",
                "hgvsp": "p.Arg408Trp",
                "effect": "missense_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 92,
                "ref_depth": 50,
                "alt_depth": 42,
                "vaf": 0.457,
                "gnomad_af": 0.0015,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Pathogenic",
                "clinvar_sig_primary": "Pathogenic",
                "clinvar_revstat": "reviewed by expert panel",
                "clinvar_stars": 4,
                "clinvar_dn": "Phenylketonuria",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs5030858",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs5030858",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Phenylketonuria",
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "VUS",
                "acmg_criteria": ["PM1", "PM2", "PP3"],
                "diseases": [
                    {"name": "Phenylketonuria", "omim": "261600", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0001249", "name": "Intellectual disability"},
                ],
            },
            {
                "variant_id": "chr1_155235843_T_C",
                "chrom": "chr1",
                "pos": 155235843,
                "ref": "T",
                "alt": "C",
                "gene": "GBA",
                "transcript": "NM_000157.4",
                "canonical_enst": "ENST00000327247",
                "hgvsc": "c.1226A>G",
                "hgvsp": "p.Asn409Ser",
                "effect": "missense_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 78,
                "ref_depth": 40,
                "alt_depth": 38,
                "vaf": 0.487,
                "gnomad_af": 0.0035,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Pathogenic/Likely pathogenic",
                "clinvar_sig_primary": "Pathogenic",
                "clinvar_revstat": "criteria provided, multiple submitters",
                "clinvar_stars": 2,
                "clinvar_dn": "Gaucher disease",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs76763715",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs76763715",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Gaucher disease",
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "VUS",
                "acmg_criteria": ["PM1", "PM5", "BP1"],
                "diseases": [
                    {"name": "Gaucher disease, type 1", "omim": "230800", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0001744", "name": "Splenomegaly"},
                    {"hpo_id": "HP:0002240", "name": "Hepatomegaly"},
                ],
            },
            {
                "variant_id": "chr17_3400410_G_A",
                "chrom": "chr17",
                "pos": 3400410,
                "ref": "G",
                "alt": "A",
                "gene": "ASPA",
                "transcript": "NM_000049.4",
                "canonical_enst": "ENST00000261903",
                "hgvsc": "c.854A>C",
                "hgvsp": "p.Glu285Ala",
                "effect": "missense_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 82,
                "ref_depth": 44,
                "alt_depth": 38,
                "vaf": 0.463,
                "gnomad_af": 0.0008,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Pathogenic",
                "clinvar_sig_primary": "Pathogenic",
                "clinvar_revstat": "reviewed by expert panel",
                "clinvar_stars": 4,
                "clinvar_dn": "Canavan disease",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs28940279",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs28940279",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": "DM",
                "hgmd_disease": "Canavan disease",
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "Likely benign",
                "acmg_criteria": ["BS1", "BP6"],
                "diseases": [
                    {"name": "Canavan disease", "omim": "271900", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [
                    {"hpo_id": "HP:0002059", "name": "Cerebral atrophy"},
                ],
            },
            {
                "variant_id": "chr9_97861232_G_A",
                "chrom": "chr9",
                "pos": 97861232,
                "ref": "G",
                "alt": "A",
                "gene": "FANCC",
                "transcript": "NM_000136.3",
                "canonical_enst": "ENST00000289081",
                "hgvsc": "c.456+4A>T",
                "hgvsp": None,
                "effect": "splice_donor_variant",
                "zygosity": "HOM",
                "gt": "1/1",
                "dp": 70,
                "ref_depth": 2,
                "alt_depth": 68,
                "vaf": 0.971,
                "gnomad_af": 0.12,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Likely benign",
                "clinvar_sig_primary": "Likely benign",
                "clinvar_revstat": "criteria provided, multiple submitters",
                "clinvar_stars": 2,
                "clinvar_dn": "Fanconi anemia",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs200000003",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs200000003",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": None,
                "hgmd_disease": None,
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "Likely benign",
                "acmg_criteria": ["BA1", "BP4"],
                "diseases": [
                    {"name": "Fanconi anemia, complementation group C", "omim": "227645", "inheritance": "AR"},
                ],
                "hpo_phenotypes": [],
            },
            {
                "variant_id": "chr19_7587500_C_T",
                "chrom": "chr19",
                "pos": 7587500,
                "ref": "C",
                "alt": "T",
                "gene": "MCOLN1",
                "transcript": "NM_020533.3",
                "canonical_enst": "ENST00000264079",
                "hgvsc": "c.406-2A>G",
                "hgvsp": None,
                "effect": "splice_acceptor_variant",
                "zygosity": "HET",
                "gt": "0/1",
                "dp": 95,
                "ref_depth": 50,
                "alt_depth": 45,
                "vaf": 0.474,
                "gnomad_af": 0.045,
                "gnomad_source": "gnomAD_exome",
                "clinvar_sig": "Benign",
                "clinvar_sig_primary": "Benign",
                "clinvar_revstat": "criteria provided, multiple submitters",
                "clinvar_stars": 2,
                "clinvar_dn": "not provided",
                "clinvar_conflicting": False,
                "dbsnp_rsid": "rs200000004",
                "dbsnp_url": "https://www.ncbi.nlm.nih.gov/snp/rs200000004",
                "clingen_hi_score": None,
                "clingen_ts_score": None,
                "hgmd_class": None,
                "hgmd_disease": None,
                "curated_classification": None,
                "curated_source": None,
                "inheritance": "AR",
                "acmg_classification": "Benign",
                "acmg_criteria": ["BA1"],
                "diseases": [],
                "hpo_phenotypes": [],
            },
        ],
    }

    result_path = os.path.join(output_dir, "result.json")
    with open(result_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"Created mock result.json at: {result_path}")
    print(f"  - {len(result['variants'])} variants")
    return result_path


def inject_mock_job():
    """
    service-daemon의 QueueManager에 mock Job을 주입합니다.
    daemon이 실행 중일 때 HTTP API를 통해 주입합니다.
    """
    import requests

    # 먼저 output 디렉토리 생성 및 result.json 배치
    output_dir = "/tmp/carrier-screening/output/test/SAMPLE_001"
    create_mock_result_json(output_dir, "SAMPLE_001")

    # 또한 variants.tsv도 생성
    variants_tsv_path = os.path.join(output_dir, "variants.tsv")
    with open(variants_tsv_path, "w") as f:
        f.write("variant_id\tgene\thgvsc\thgvsp\teffect\tacmg_classification\n")
        f.write("chr7_117559590_G_A\tCFTR\tc.1521_1523delCTT\tp.Phe508del\tinframe_deletion\tPathogenic\n")
    print(f"Created mock variants.tsv at: {variants_tsv_path}")

    # daemon에 mock job 주입 (submit API 사용)
    # 이 경우 실제 파이프라인은 실행되지 않지만, job이 등록됩니다.
    # 대신 직접 QueueManager에 접근하는 내부 엔드포인트를 사용합니다.
    print("\nTo inject mock data, use the following curl command:")
    print(f"""
curl -X POST http://localhost:8000/order/carrier_screening/submit \\
  -H "Content-Type: application/json" \\
  -d '{{
    "order_id": "CS-TEST-001",
    "service_code": "carrier_screening",
    "sample_name": "SAMPLE_001",
    "work_dir": "test",
    "fastq_r1_path": "/tmp/test_R1.fastq.gz",
    "fastq_r2_path": "/tmp/test_R2.fastq.gz",
    "params": {{}},
    "priority": "normal"
  }}'
""")


if __name__ == "__main__":
    # 기본: mock result.json만 생성
    output_dir = "/tmp/carrier-screening/output/test/SAMPLE_001"
    create_mock_result_json(output_dir)
    inject_mock_job()
